### ISSUE TITLE
FactorModelSigma -> FactorModelCovariance

### ISSUE THREAD

**Issue by wec7** [cvxgrp/cvxportfolio#102]
Hi @enzbus, 

I noticed the implementation of `FactorModelSigma` (renamed as `FactorModelCovariance`) has changed from `F D F^T` to `F F^T` where F is factor loadings, and D was the factor sigma (or factor covariance).

Just curious any reasons? I can try implement and send PR to add factor_Sigma back, but prior to that, may I make sure if any bottlenecks you've experienced?

Old implementation - 
https://github.com/cvxgrp/cvxportfolio/blob/1786671014f6cdbc539976b2e2795c02be31355d/cvxportfolio/risks.py#L157-L162

New implementation: https://github.com/cvxgrp/cvxportfolio/blob/a94f9c1de3e4fb92943d029a662202d9887ea37f/cvxportfolio/risks.py#L295-L304

Thanks,

**Comment by enzbus** [comment]
Hello, this has been added with commit 7827bc6 , I'll make a release probably today. I also clarified the various combination of arguments in the docstring.

**Comment by wec7** [comment]
Thank you very much
