### ISSUE TITLE
I

### ISSUE THREAD

**Issue by pcgm-team** [cvxgrp/cvxportfolio#115]

**Comment by enzbus** [comment]
The `min_history` parameter could be relevant there. You probably need to set it to something like `pd.Timedelta('7d')` or `pd.Timedelta('0d')` if you want all data to be used. The default is one year. It is used to keep assets that recently IPO'd out of back-tests.

**Comment by enzbus** [comment]
Yeah by looking at `_earliest_backtest_start` in `data.py` I suspect that's what happened. I'll reopen to this to remind me to add better error checking there.
