### ISSUE TITLE
NaN Handling

### ISSUE THREAD

**Issue by pcgm-team** [cvxgrp/cvxportfolio#116]
In the case of NaNs in the predicted return dataframe as well as the provided data, the default behavior should be:

1. Ignore the NaNs when calculating running the optimization at each timestamp.
2. Set weights to zero for all positions with a NaN in the data at that timestamp.

Most finance datasets will have a prevalence of NaNs that cannot really be work-arounded by backtesting in groups etc. (stocks go in and out of the universe, etc etc.)

**Comment by enzbus** [comment]
Hello! I'm not sure I understand, sorry. Data that is fed to the optimization routines can never have `np.nan`. Historical market data is managed, in this case, by `UserProvidedMarketData`. Its default behavior is to look at the `returns` dataframe and at every time step only include in the back-test (or online execution) names that have non-nan return for the period and have had non-nan returns for at least a `min_history` time period. The interface is defined in the `MarketData` base class, so if you want a different behavior you can derive from there (it only has 3 public methods). The default one defines its logic in `MarketDataInMemory` so you may as well redefine the one or two methods that have to do with the asset selection (I may make it easier to do in the future). `MarketSimulator` also has logic to decide what to do if an asset is dropped during a back-test, the default behavior is to liquidate (transform in cash) without transaction cost, assuming it's an M&A kind of situation. In general the default behavior are designed around daily trading of stocks in the US, but any other can be achieved by deriving from the default objects.

**Comment by enzbus** [comment]
Reopening this because I need to improve docs on it.

**Comment by enzbus** [comment]
You should post the stack trace, there are many pieces that could throw a nan error. `values_in_time` is the method called by all elements of a policy at each point in time of a back-test. If you're sure the error comes from the `ReturnsForecast` then it could be a missing or misaligned timestamp, or a missing asset. Do you have constant or varying universe?
