### ISSUE TITLE
MultiPeriodOptimization Behavior Documentation

### ISSUE THREAD

**Issue by pcgm-team** [cvxgrp/cvxportfolio#117]
With user provided returns forecast, with a single forecasted return per timestamp- how does the model use the forecast?

Is it looking at the next `planning_horizon` bars of forecast on that day (lookahead-biasing if you generated the forecast with data upto that timestamp); or is it persisting the same forecast for `planning_horizon` additional bars of optimization.

I've read the docs and paper, but the way it is implemented is very unclear.

**Comment by enzbus** [comment]
Hello, I also need to improve the docs on this. There are two ways to do it. One is to build a MPO policy by providing a list of objectives and a list of lists of constraints:

```
mpo_policy = cvx.MultiPeriodOptimization(
    objective = [cvx.ReturnsForecast(signal_today_dataframe) - gamma_risk * cvx.FullCovariance() - ...,
                         cvx.ReturnsForecast(signal_tomorrow_dataframe) - gamma_risk * cvx.FullCovariance() - ...]
    constraints = [[cvx.LeverageLimit(3)],
                           [cvx.LeverageLimit(3)]]
)
```
so the `planning_horizon` argument is unused. In this way you can change all the terms you want for each MPO step. 

The other, in case you simply have *slow* and *fast* signals, is to use the `decay` argument of `ReturnsForecast`

```
mpo_policy = cvx.MultiPeriodOptimization(
    objective = cvx.ReturnsForecast(fast_signal_dataframe, decay = .2)
                       + cvx.ReturnsForecast(slow_signal_dataframe, decay = .8)
                       - gamma_risk * cvx.FullCovariance() , 
    constraints = [cvx.LeverageLimit(3)],
    planning_horizon = 5,
)
```

Let me know if this answers your question.

**Comment by pcgm-team** [comment]
Thank you that clarifies perfectly. Very helpful.

**Comment by enzbus** [comment]
I need to improve the docs for this; it might take a while so at least if someone comes here to ask something similar they find this.

**Comment by pcgm-team** [comment]
so if I have a dataframe of signal_day_after_tomorrow (indices are the date the signals are created) I should shift it forward by two when I feed it into the objective?

**Comment by enzbus** [comment]
I think in your formalism (comment before) it's `t+1 pred t+1` for signal today, and so on. The timestamp in the signal dataframe is such that the prediction at that timestamp is done using all data up to the price at that timestamp. For signals for the future it's the same, but you predict a future quantity.

**Comment by pcgm-team** [comment]
I'm still not 100% sure, but it sounds like basically if I got signal1 and and signal2 with index being the index outputted by a regression (so the date at which we predict target return of next day for signal1, and then that target shifted back by 1 for signal2); the correct way to use the optimizer would be something like:

```mpo_policy = cvx.MultiPeriodOptimization(
    objective = [cvx.ReturnsForecast(signal1.shift(1)) - gamma_risk * cvx.FullCovariance() - ...,
                cvx.ReturnsForecast(signal2.shift(2)) - gamma_risk * cvx.FullCovariance() - ...]
    constraints = [[cvx.LeverageLimit(3)],
                [cvx.LeverageLimit(3)]]
)```

**Comment by enzbus** [comment]
You've got to think about the way data is consumed by your machine learning model that produces the signal. That's why you can take the user provided forecasters example as a starting point https://github.com/cvxgrp/cvxportfolio/blob/master/examples/user_provided_forecasters.py .

The line of your signal that has timestamp `t`, **must** be built with data that was available at time `t`. That's the case for all forecasted quantities: returns for the period, for the next period, volumes, risk model parameters, .... (If you don't have that property you're doing look-ahead and any analysis is invalid.)

**Comment by pcgm-team** [comment]
This question is more clear and will help me understand the exact behavior:

If I call MultiPeriodOptimization with two objectives and I'm doing a single step execute.

```
mpo_policy = cvx.MultiPeriodOptimization(
    objective = [cvx.ReturnsForecast(step1) - gamma_risk * cvx.FullCovariance() - ...,
                cvx.ReturnsForecast(step2) - gamma_risk * cvx.FullCovariance() - ...,
                cvx.ReturnsForecast(step3) - gamma_risk * cvx.FullCovariance() - ...,
]
constraints = [[cvx.LeverageLimit(3)], [cvx.LeverageLimit(3)], [cvx.LeverageLimit(3)]]
u, t, shares_traded = mpo_policy.execute(h=h, market_data=market_data)
)
```
Should the step1, step2, and step3 have the same index?

**Comment by enzbus** [comment]
An improved explanation of the multi-period optimization model was just merged in master, can be seen on the development version of the docs https://www.cvxportfolio.com/en/master/manual.html#multi-period-optimization

**Comment by miller-moore** [comment]
Hi @enzbus, I'm trying to generate my own MPO backtest example since the one in the [docs](https://www.cvxportfolio.com/en/stable/examples/paper_examples/multi_period_opt.html) is not yet complete. Currently I am getting a MissingTimesError that isn't caused by a timezone mismatch. In my case it is probably a misspecification between the ReturnsForecast dataframes and my user provided market data. In any case, do you have an estimate for when the example may be complete? I could work up an MRE if you think there could be a bug in the loop over trading calendar indices. Thanks

**Comment by enzbus** [comment]
Does the section in the manual -> https://www.cvxportfolio.com/en/stable/manual.html#multi-period-optimization or this work-in-progress thesis ->

**Comment by miller-moore** [comment]
Yes I have read the full docs and the full paper. My forecast dataframes and market-data dataframes are both indexed by open timestamps. The forecast values corresponds to the forecasted return in the periods that follow while the market data `returns` dataframe contains the actual returns in the periods that follow.

For example, by my formalism with a planning period of 3, `signal_today_dataframe` has index _open\_t_ and the forecast corresponds to the period between _open\_t_ and _open\_t+1_, `signal_next_dataframe` has index _open\_t_ and the forecast corresponds to the period between _open\_t+1_ and _open\_t+2_, and finally `signal_next_next_dataframe` has index _open\_t_ and the forecast corresponds to the period between _open\_t+2_ and _open\_t+3_.

Regarding market data, my `returns` dataframe also has index _open\_t and the return value corresponds to the actual return between _open\_t_ and _open\_t+1_ and its index (_open\_t_) is identical to each forecast dataframe index. Is this structure the correct expectation per the API and is it true that all forecasted dataframes need to have an identical index to each market-data dataframe?

My desire for an example with data is simply that it could help clear up any ambiguity in the expectation of mutual structure between the forecasts and market-data but answers to the above should be enough to get me there eventually.

Thanks

**Comment by enzbus** [comment]
Thanks for the clarifications, and yes that is indeed the correct format. I don't have an ETA for the complete restoration of the 2016 example notebooks, but if you paste a trace-back of the specific error you're getting I might help.

**Comment by miller-moore** [comment]
I will generate an MRE if I continue to have trouble. Thank you for the verification!
