### ISSUE TITLE
do_asset_selection potential bug

### ISSUE THREAD

**Issue by pcgm-team** [cvxgrp/cvxportfolio#123]
Potential bug, according to the documentation
```
cvx.UserProvidedMarketData(returns = self.returns, volumes = self.volume*self.open, prices = self.open, do_asset_selection = False)

TypeError: UserProvidedMarketData.__init__() got an unexpected keyword argument 'do_asset_selection'
```
I checked that my version number is 1.0.3

**Comment by enzbus** [comment]
Yes, That's because I added it yesterday. I'll try to fix the documentation to the pip version (now it tracks the current repository state).

**Comment by enzbus** [comment]
Ok, now when you navigate to https://www.cvxportfolio.com you should be redirected to https://www.cvxportfolio.com/en/stable/ (before it was https://www.cvxportfolio.com/en/latest/ ). You may have to refresh your browser cache (open a private window) to see that. You can see more versions in the banner on the bottom left.

**Comment by enzbus** [comment]
@pcgm-team see also #121
