### ISSUE TITLE
Propose to change the definition of Leverage in LeverageLimit constraint.

### ISSUE THREAD

**Issue by mickeydonkey** [cvxgrp/cvxportfolio#14]
https://github.com/cvxgrp/cvxportfolio/blob/feb45aa0d1bfc2e9f80070eb1353a02da34db047/cvxportfolio/constraints.py#L116
Here we include cash when calculate leverage.

And Since the term leverage is overused and vague, I find the definition of gross exposure which is similar to leverage above except the weight of cash.  
https://www.investopedia.com/terms/g/gross-exposure.asp

IMHO, the limit on gross exposure makes more sense than the leverage we used here. Consider a long-only and long-cash portfolio whose leverage is constant and gross exposure may vary. So I prefer to exclude weight of cash here.

**Comment by joseortiz3** [comment]
The term "leverage" is generally very vague, but it is and should be defined by the paper's definition of leverage.

The definition of "gross exposure" you provided appears to be identical to the paper's definition of leverage, when you consider "percent (fractional) gross exposure".

> Gross exposure refers to the absolute level of a fund's investments. Gross exposure equals the value of both a fund’s long positions and short positions and can be expressed **either in dollar terms or percentage terms.** It is a measure that indicates total exposure to financial markets, thus providing an insight into the investment amount at risk. The higher the gross exposure, the bigger the potential loss (or gain).

In the "percent" case, the following does not make sense "Consider a long-only and long-cash portfolio whose leverage is constant and gross exposure may vary." In this case they are the same thing.

If you are talking about a _cash_ limit on gross exposure, that should be an entirely different class definition, maybe `def class CashGrossExposureLimit`.

IMO if anything should be changed it should be the documentation underneath the class definition (and probably every other class definition while your at it haha).

```python
class LeverageLimit(BaseConstraint):
    """A limit on leverage.
    Attributes:
      limit: A series or number giving the leverage limit.
    """
```

```python
class LeverageLimit(BaseConstraint):
    """A limit on leverage. Leverage is defined as the absolute value of all non-cash holdings, divided by the total portfolio value.
    Attributes:
      limit: A series or number giving the leverage limit.
    """
```

**Comment by mickeydonkey** [comment]
Yes, I agree documentation is helpful and thanks to point out the cvxportfolio paper's definition of gross exposure and leverage is consistent with the link I provided. To account for "all non-cash holdings" the returned value(IMO) should be `return cvx.norm(w_plus[:-1], 1) <= limit ` .

**Comment by joseortiz3** [comment]
Oh, wow, sorry. Now I understand what you're saying. Sometimes I am very bad at reading.

Yes, I agree. It seems leverage should be `cvx.norm(w_plus[:-1], 1) <= limit`, because `w_plus` has n+1 elements (it includes cash). Good catch. Right?

**Comment by enzobusseti** [comment]
@mickeydonkey @joseortiz3 you are right, there's a a discrepancy between the paper and the code, thanks for finding it.

**Comment by enzobusseti** [comment]
There's a caveat though. Ignoring cash from the portfolio leverage makes only sense when cash is non-negative. For example the portfolio:
```
AAPL: $10000
USDOLLAR: $-5000
```
is leveraged, in the sense that the investor only owns about $5k but has $10k exposed in the market.

Here's what I'll do:

- define a `ClassicLeverageLimit` constraint that does what is suggested in the paper (*i.e.*, `cvx.norm(w_plus[:-1], 1) <= limit`)
- define `LeverageLimit` as the concatenation (constraints are becoming lists of `cvxpy` expressions) of `ClassicLeverageLimit` and `LongCash`
- define a `TotalLeverageLimit` as the current `LeverageLimit` (*i.e.*, `cvx.norm(w_plus, 1) <= limit`)

Personally, I'd suggest using the `TotalLeverageLimit` if in doubt. (It expresses better the fact that the investor is risking more money than he or she has.)

**Comment by enzobusseti** [comment]
Yep, you're right. I haven't expressed this correctly. Let me think about it. (My doubt is that, by taking cash out of the leverage constraint, a short cash position is not penalized in the same way as a short in any other asset.)

**Comment by enzobusseti** [comment]
You're right, I'm closing this.
