### ISSUE TITLE
Question on long-only constraint

### ISSUE THREAD

**Issue by mickeydonkey** [cvxgrp/cvxportfolio#17]
The definition of long-only constraint in source code includes last cash term, i.e. the weight of cash should be non-negative.
https://github.com/cvxgrp/cvxportfolio/blob/152188adac72c1bce85f1aa526e85b4f611cf497/cvxportfolio/constraints.py#L93

On the other side, I notice there is a inconsistency in the paper with respect to this constraint.

Def 1:
In page 7 line 8, it says "The portfolio is long-only when the asset holdings are all nonnegative, i.e.,(h_t)_i ≥ 0 for i = 1, . . . ,n" This definition ignores the cash, which is n+1 th term of h_t

Def 2:
While in page33, Long only. "This constraint requires that only long asset positions are
held, wt + zt ≥ 0."  which requires cash to be nonnegative.

I personally perfer the 1st definition, IMO it is more intuitive and one can combine this long-only constraint with the long-cash constraint to compose the current long-only constraint.

**Comment by enzobusseti** [comment]
Thanks for catching this! It's probably better to leave it as it is, and maybe adding a `LongAssets` constraint to complement `LongCash`. I'll think about it.
