### ISSUE TITLE
MultiPeriodOpt with lookahead_periods>2 fails

### ISSUE THREAD

**Issue by optwave** [cvxgrp/cvxportfolio#18]
When lookahead_periods > 2, I get the following error:
```
File "PATH\cvxportfolio\returns.py", line 103, in weight_expr_ahead
    return self.alpha_data[(t, tau)].values.T * wplus
KeyError: (Timestamp('2012-01-03 00:00:00'), Timestamp('2012-01-05 00:00:00'))
```

**Comment by joseortiz3** [comment]
Your data-structure is not indexed correctly. The key its looking for is `self.alpha_data[(Timestamp('2012-01-03 00:00:00'), Timestamp('2012-01-05 00:00:00'))]`, but it couldn't find it because your `alpha_data` is not structured that way.

**Comment by optwave** [comment]
Thanks, @joseortiz3 !
I use the original data provided with the package. The following code solved the issue:
```
    M = 1 # to set lookahead_periods=M for MultiPeriodOpt(...) 
    for i, t in enumerate(returns.index[:-M]):
        all_return_estimates[(t, t)] = return_estimate.loc[t]
        for j in range(1, M):
            tpj = returns.index[i + j]
            all_return_estimates[(t, tpj)] = return_estimate.loc[tpj]
```
