### ISSUE TITLE
Missing MPOReturnsForecast.weight_expr

### ISSUE THREAD

**Issue by jonathanng** [cvxgrp/cvxportfolio#2]
When running MultiPeriodOptimization.ipynb, getting the error:

> Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr

**Comment by heshriti** [comment]
I too have this issue. Any resolution on this.

**Comment by heshriti** [comment]
cvxportfolio TypeError: Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr

**Comment by enzobusseti** [comment]
This should be fixed now.

**Comment by heshriti** [comment]
sorry, didnt work. I get the same error.

>>> returns_forecast = cp.MPOReturnsForecast(all_return_estimates)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr

**Comment by enzobusseti** [comment]
the bug is fixed in the repo. you probably have an older version installed (i.e., from pip).

follow these steps:
`git clone  https://github.com/cvxgrp/cvxportfolio.git`
`cd cvxportfolio`
`conda env create -f test_environment.yml`
`source activate`
`jupyter notebook`
`source deactivate`

and then run the examples. you can also install the package with 
`python setup.py install`

**Comment by heshriti** [comment]
unfortunately, I don't have conda in bsd_os. 

the python setup.py install seems to have worked, and when I tried to rerun example, I get the same error. 
Is it possible to dist the package update in pip; and a simple example to check for the "abstract class error "

**Comment by heshriti** [comment]
Is it possible to have this in pip.

After hours of frustration, I gve up trying install 'condo' or 'python
setup install.'. Too many errors to list.
pip insall works. Can you please package cvxportfolio into pip?

thanks

**Comment by kch382001** [comment]
I have same problem here. Can you package the fix to cvxportfolio into pip?

**Comment by CraigAlanFriedman** [comment]
Same problem (TypeError: Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr) using pip install cvxportfolio on colab.  Any suggestions?

Many thanks
