### ISSUE TITLE
trying the hello world program - python errors

### ISSUE THREAD

**Issue by andrewcz** [cvxgrp/cvxportfolio#20]
Hi !
Really love the framework and planning to get involved.
was wanting to expand for a masters project.
i am trying to run the hello world program and getting the following -

risk_model = cp.FullSigma(Sigma_hat)
gamma_risk, gamma_trade, gamma_hold = 5., 1., 1.
leverage_limit = cp.LeverageLimit(3)

spo_policy = cp.SinglePeriodOpt(return_forecast=r_hat, 
                                costs=[gamma_risk*risk_model, gamma_trade*tcost_model, gamma_hold*hcost_model],
                                constraints=[leverage_limit])
risk_model = cp.FullSigma(Sigma_hat)
gamma_risk, gamma_trade, gamma_hold = 5., 1., 1.
leverage_limit = cp.LeverageLimit(3)
​
spo_policy = cp.SinglePeriodOpt(return_forecast=r_hat, 
                                costs=[gamma_risk*risk_model, gamma_trade*tcost_model, gamma_hold*hcost_model],
                                constraints=[leverage_limit])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-d5c4e92f2ffa> in <module>()
      5 spo_policy = cp.SinglePeriodOpt(return_forecast=r_hat, 
      6                                 costs=[gamma_risk*risk_model, gamma_trade*tcost_model, gamma_hold*hcost_model],
----> 7                                 constraints=[leverage_limit])

~/cvxportfolio/cvxportfolio/policies.py in __init__(self, return_forecast, costs, constraints, solver, solver_opts)
    217 
    218         if not isinstance(return_forecast, BaseReturnsModel):
--> 219             null_checker(return_forecast)
    220         self.return_forecast = return_forecast
    221 

~/cvxportfolio/cvxportfolio/utils/data_management.py in null_checker(obj)
     27         isinstance(obj, pd.DataFrame) or
     28             isinstance(obj, pd.Series)):
---> 29         if np.any(pd.isnull(obj)):
     30             raise ValueError('Data object contains NaN values', obj)
     31     elif np.isscalar(obj):

~/tutorial-env2/lib/python3.6/site-packages/pandas/core/generic.py in __nonzero__(self)
   1571         raise ValueError("The truth value of a {0} is ambiguous. "
   1572                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
-> 1573                          .format(self.__class__.__name__))
   1574 
   1575     __bool__ = __nonzero__

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

was wondering if you could assist.
Best,
Andrew

**Comment by enzobusseti** [comment]
it looks like there are `NaN` values in the return forecast, could you inspect it? it could be an issue with the data source...

**Comment by andrewcz** [comment]
![screenshot_2018-08-20_20-25-21](https://user-images.githubusercontent.com/2296335/44335307-59f50380-a4b7-11e8-911a-1b9c942f07d1.png)

**Comment by andrewcz** [comment]
not sure whats going on.

**Comment by andrewcz** [comment]
so interesting, r_hat.all() seems to have worked?
I'm not sure why and to be honest I am not sure if this is mathematically correct.
How would could I find out?
Best,
Andrew

**Comment by enzobusseti** [comment]
sorry but i can reproduce your error and i don't have enough information for understanding what's wrong. can you isolate the error in a (short) python script and post it here?

**Comment by andrewcz** [comment]
Hi Enzo,
Champion!
Its probably my mistake.
Will try it again tonight with updated packages.
Many thanks
Best,
Andrew

**Comment by andrewcz** [comment]
Hi Enzo!
So i have updated pandas and everything looks like its working.
however, on the real-time optimization example, I get the following error -

![screenshot_2018-08-22_20-55-59](https://user-images.githubusercontent.com/2296335/44459679-d4f02280-a64d-11e8-90d5-179180a29719.png)


Best,
Andrew

**Comment by andrewcz** [comment]
![screenshot_2018-08-22_21-29-41](https://user-images.githubusercontent.com/2296335/44460959-71b4bf00-a652-11e8-9b37-3dd665225f08.png)

**Comment by enzobusseti** [comment]
(1)  take away the .shift(…) method, it’s not important (and maybe got broken by a pandas update) 

(2) AlphaSource was the old name of ReturnForecast, please double check (it’s possible that the solutiontime example hasn’t been updated in a long time)

good luck!
