### ISSUE TITLE
Noticeable Speed Loss Per Discrete Time Interval With Minutely Data

### ISSUE THREAD

**Issue by ghost** [cvxgrp/cvxportfolio#24]
I successfully ran your Jupyter notebook examples using the daily Quandl data and was impressed with the speed; however, when I insert e.g., minutely data, the speed per minute with minutely data is much, much slower than the speed per day with daily data. The difference is ca x20 times larger. How can this be rectified?

**Comment by enzbus** [comment]
Hello, I'm not sure about this. The cost per iteration of the simulator and solver should not depend on the number of iterations.
