### ISSUE TITLE
Error out on Policy.py when running MPO example

### ISSUE THREAD

**Issue by kch382001** [cvxgrp/cvxportfolio#34]
When running MPO example, I got error message on this line in policy.py file: 

 z = cvx.Variable(*w.size)   #----- Error Out
wplus = w + z 

   It looks like the line does not work for  any cvxpy version > cvxpy1.0.  Need to change it to 
z = cvx.Variable(w.size) to make it work.

**Comment by kch382001** [comment]
It would be nice if all these issues are fixed. And at least we can get these jupyter notebook examples to run through without problem.

**Comment by joseortiz3** [comment]
Hello @kch382001. Thanks for finding the errors in the example code. I know I had to fix a few of them to get mine to run.

When you make an issue on github, here or anywhere, please specify more detail about what the error is, in which file and on what line the error is at, and why the error occurs if known. Also please format you code by using the github formatting options, such as

```python
z = cvx.Variable(*w.size) #----- Error Out
wplus = w + z
```
And include what versions of relevant packages you are using. Also please provide the full output of any error including stack trace.

**Comment by kch382001** [comment]
Thanks for the reply. Will follow the github convention in the future. The cvxportfolio is a good framework, a faithful implementation of the paper. It would be great to see higher usage in the future if these bugs are fixed.  There are several issues related to different version of numpy, python and cvx. I opened new issues on these bugs. 
   Thanks for the quick reply. Really appreciate it.

**Comment by joseortiz3** [comment]
@kch382001 You should also write descriptive titles about what the error is specifically, not "error out".

**Comment by kch382001** [comment]
Sorry. Will do next time.  
I guess this package is not well maintained. So many obvious bugs.
