### ISSUE TITLE
Pandas Panel replacement.

### ISSUE THREAD

**Issue by kch382001** [cvxgrp/cvxportfolio#39]
The current cvxportfolio uses Pandas.Panel data structure.  According to Pandas development, Panel is deprecated and will be removed in future version. I do not know what this means.  But for cvxportfolio, is there a plan to replace Panel data structure in future release?

**Comment by joseortiz3** [comment]
Pandas panels are deprecated, but they've been saying that for at least a year now. You are fine just ignoring it. If they ever do remove it, the Panels will have to be replaced with 2d-by-1d MultiIndex DataFrames, or dictionaries of 1d-by-1d dataframes. But personally I doubt they will remove Panel. There is only a slight difference in construction and indexing. If you want to, you can insert code into your own fork for handling MultiIndex dataframes and submit a pull request.
