### ISSUE TITLE
MultiPeriodOptimization example problem

### ISSUE THREAD

**Issue by genlirady** [cvxgrp/cvxportfolio#4]
Hi,

When I run your MultiPeriodOptimization example, in the first part of MPO Coarse search, I get the error: 
**TypeError: __init__() got an unexpected keyword argument 'alpha_model'**. Then, I delete "alpha_model =" characters and keep everything else unchanged. However, I still get error saying 
**__init__() got multiple values for argument 'trading_times'**.

Could you tell me how I can fix it?

**Comment by genlirady** [comment]
I have found where the problem is. In file policies.py, I change all arguments “return_forecast” to “alpha_model” and the MPO example works well. I think the problem occurs because of the inconsistency of argument name between functions.

**Comment by enzobusseti** [comment]
thanks for reporting this. i plan to fix a few of these bugs during christmas break.
