### ISSUE TITLE
null_checker requires extra np.any()

### ISSUE THREAD

**Issue by thayes75** [cvxgrp/cvxportfolio#44]
I'm wondering if it's perhaps a result of new pandas behaviour, but I had to change the null_checker (line 29 in data_management.py) to read as:

`        if np.any( np.any(np.any(pd.isnull(obj))) ):`

for the HelloWorld example to run. Seems to be an issue in that it spits out a series of "False" values and it requires a single bool value. Can anyone confirm? I'm on Pandas 0.20.3.

**Comment by kch382001** [comment]
I had same issue.  You are right. It is because pandas behavior changed with newer version

**Comment by joseortiz3** [comment]
If that is the case, you should probably use `np.any(pd.isnull(obj).values.reshape(1,-1))` so that the code doesn't assume the object is a `pd.Panel`.

**Comment by thayes75** [comment]
null checker still has the above issue with 0.0.12.
