### ISSUE TITLE
MPO example failing since cvxportfolio is incompatible with pandas >= 0.25

### ISSUE THREAD

**Issue by TBaltensperger** [cvxgrp/cvxportfolio#45]
When running the MPO example it fails when trying to access the data loaded into risk_data:

`
In[3]: risk_data.exposures
`
`
Traceback (most recent call last):
  File "/home/xxx/envs/cvxportfolio/lib/python3.6/site-packages/pandas/io/pytables.py", line 1423, in _create_storer
    return globals()[_STORER_MAP[pt]](self, group, **kwargs)
KeyError: 'wide'
`

I assume this is due to a wrong version of pandas. I am using pandas 0.25.1 and python 3.6, but read in thread #44 that some people use pandas 0.20.3. Could someone provide a complete list of the packages compatible with cvxportfolio?

**Comment by TBaltensperger** [comment]
I could track down the issue, pandas 0.25 dropped support for panels, therefore the data stored in `risk_model.h5` can't be correctly loaded. In fact, the file `risk_model.h5` can also no longer be produced either in `DataEstimatesRiskModel.ipynb`. Maybe further compatibility issues with pandas 0.25 exist

**Comment by sankethvedula** [comment]
I think the support for Panels was dropped post `pandas==0.24.0` -- this is the latest version that works for me.

**Comment by roprisor** [comment]
I have an open pull request that fixes latest pandas compatibility issues, another option aside from downgrading pandas: https://github.com/cvxgrp/cvxportfolio/pull/41

**Comment by enzobusseti** [comment]
Hi! Apologies for the late reply, I only recently had some time to spend on `cvxportfolio`. I'm currently changing the way data is provided MPO, by using callable objects that take two arguments: the time `t` of trading, and a `steps_ahead` integer (that is 0 for SPO). It will be clearer once I finish it.

**Comment by VanBuren77** [comment]
I git cloned the latest version and this appears to still be an issue
