### ISSUE TITLE
HelloWorld.ipynb failing

### ISSUE THREAD

**Issue by gobbedy** [cvxgrp/cvxportfolio#47]
Hello,

I ran the HelloWorld jupyter notebook on both a Linux VM and a Mac (actual Mac, not VM), and got the same error. Pasted below is the code of the failing cell (the 7th cell) followed by the output of the cell:

```
market_sim=cp.MarketSimulator(returns, [tcost_model, hcost_model], cash_key='USDOLLAR') 
init_portfolio = pd.Series(index=returns.columns, data=250000.)
init_portfolio.USDOLLAR = 0
results = market_sim.run_multiple_backtest(init_portfolio,
                               start_time='2013-01-03',  end_time='2016-12-31',  
                               policies=[spo_policy, cp.Hold()])
results[0].summary()
```
---------------------------------------------------------------------------

> RemoteTraceback                           Traceback (most recent call last)
> 
> RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/gperraul/anaconda3/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/gperraul/anaconda3/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/home/gperraul/PycharmProjects/cvxportfolio/cvxportfolio/simulator.py", line 147, in _run_backtest
>     policy, loglevel=loglevel)
>   File "/home/gperraul/PycharmProjects/cvxportfolio/cvxportfolio/simulator.py", line 116, in run_backtest
>     u = policy.get_trades(h, t)
>   File "/home/gperraul/PycharmProjects/cvxportfolio/cvxportfolio/policies.py", line 265, in get_trades
>     cost_expr, const_expr = cost.weight_expr(t, wplus, z, value)
>   File "/home/gperraul/PycharmProjects/cvxportfolio/cvxportfolio/risks.py", line 58, in weight_expr
>     self.expression = self._estimate(t, w_plus - self.w_bench, z, value)
>   File "/home/gperraul/PycharmProjects/cvxportfolio/cvxportfolio/risks.py", line 105, in _estimate
>     wplus, values_in_time(self.Sigma, t))
>   File "/home/gperraul/anaconda3/lib/python3.7/site-packages/cvxpy/atoms/quad_form.py", line 215, in quad_form
>     raise Exception("Invalid dimensions for arguments.")
> Exception: Invalid dimensions for arguments.
> """
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Exception                                 Traceback (most recent call last)
> 
> <ipython-input-7-4cce2fc861f0> in <module>
>       4 results = market_sim.run_multiple_backtest(init_portfolio,
>       5                                start_time='2013-01-03',  end_time='2016-12-31',
> ----> 6                                policies=[spo_policy, cp.Hold()])
>       7 results[0].summary()
>       8 
> 
> ~/PycharmProjects/cvxportfolio/cvxportfolio/simulator.py in run_multiple_backtest(self, initial_portf, start_time, end_time, policies, loglevel, parallel)
>     150         if parallel:
>     151             workers = multiprocess.Pool(num_workers)
> --> 152             results = workers.map(_run_backtest, policies)
>     153             workers.close()
>     154             return results
> 
> ~/anaconda3/lib/python3.7/site-packages/multiprocess/pool.py in map(self, func, iterable, chunksize)
>     266         in a list that is returned.
>     267         '''
> --> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
>     269 
>     270     def starmap(self, func, iterable, chunksize=None):
> 
> ~/anaconda3/lib/python3.7/site-packages/multiprocess/pool.py in get(self, timeout)
>     655             return self._value
>     656         else:
> --> 657             raise self._value
>     658 
>     659     def _set(self, i, obj):
> 
> Exception: Invalid dimensions for arguments.
> 

Do you know what might explain this error?

I used the latest Anaconda (2019.10) to install cvxpy in both the linux VM and Mac (I had errors when trying to install cvxpy using pip). Not sure if it could somehow be related to that.. Perhaps I should use an older version of the multiprocess library?

Thanks in advance.

**Comment by gobbedy** [comment]
@enzobusseti I've made a serious effort at debug, but I've made little progress. Reading the other open issues, it seems it might simply be a case of incompatible package versions.

Would you be so kind as to supply the list package versions you're using (assuming you're able to run the examples), so that I could get a known good list of dependencies for cvxportfolio?

Here is the list of packages I'm using, which yield the error described in the previous comment.
```pip list```

> Package                            Version    
> ---------------------------------- -----------
> alabaster                          0.7.12     
> anaconda-client                    1.7.2      
> anaconda-navigator                 1.9.7      
> anaconda-project                   0.8.3      
> asn1crypto                         0.24.0     
> astroid                            2.2.5      
> astropy                            3.2.1      
> atomicwrites                       1.3.0      
> attrs                              19.1.0     
> Babel                              2.7.0      
> backcall                           0.1.0      
> backports.functools-lru-cache      1.5        
> backports.os                       0.1.1      
> backports.shutil-get-terminal-size 1.0.0      
> backports.tempfile                 1.0        
> backports.weakref                  1.0.post1  
> beautifulsoup4                     4.7.1      
> bitarray                           0.9.3      
> bkcharts                           0.2        
> bleach                             3.1.0      
> bokeh                              1.2.0      
> boto                               2.49.0     
> Bottleneck                         1.2.1      
> certifi                            2019.6.16  
> cffi                               1.12.3     
> chardet                            3.0.4      
> Click                              7.0        
> cloudpickle                        1.2.1      
> clyent                             1.2.2      
> colorama                           0.4.1      
> conda                              4.8.2      
> conda-build                        3.18.8     
> conda-package-handling             1.3.11     
> conda-verify                       3.4.2      
> contextlib2                        0.5.5      
> cryptography                       2.7        
> cvxportfolio                       0.0.10.3   
> cvxpy                              1.0.28     
> cycler                             0.10.0     
> Cython                             0.29.12    
> cytoolz                            0.10.0     
> dask                               2.1.0      
> decorator                          4.4.0      
> defusedxml                         0.6.0      
> dill                               0.3.1.1    
> distributed                        2.1.0      
> docutils                           0.14       
> ecos                               2.0.7.post1
> entrypoints                        0.3        
> et-xmlfile                         1.0.1      
> fastcache                          1.1.0      
> filelock                           3.0.12     
> Flask                              1.1.1      
> future                             0.18.2     
> gevent                             1.4.0      
> glob2                              0.7        
> gmpy2                              2.0.8      
> greenlet                           0.4.15     
> h5py                               2.9.0      
> heapdict                           1.0.0      
> html5lib                           1.0.1      
> idna                               2.8        
> imageio                            2.5.0      
> imagesize                          1.1.0      
> importlib-metadata                 0.17       
> inflection                         0.3.1      
> ipykernel                          5.1.1      
> ipython                            7.6.1      
> ipython-genutils                   0.2.0      
> ipywidgets                         7.5.0      
> isort                              4.3.21     
> itsdangerous                       1.1.0      
> jdcal                              1.4.1      
> jedi                               0.13.3     
> jeepney                            0.4        
> Jinja2                             2.10.1     
> joblib                             0.13.2     
> json5                              0.8.4      
> jsonschema                         3.0.1      
> jupyter                            1.0.0      
> jupyter-client                     5.3.1      
> jupyter-console                    6.0.0      
> jupyter-core                       4.5.0      
> jupyterlab                         1.0.2      
> jupyterlab-server                  1.0.0      
> keyring                            18.0.0     
> kiwisolver                         1.1.0      
> lazy-object-proxy                  1.4.1      
> libarchive-c                       2.8        
> lief                               0.9.0      
> llvmlite                           0.29.0     
> locket                             0.2.0      
> lxml                               4.3.4      
> MarkupSafe                         1.1.1      
> matplotlib                         3.1.0      
> mccabe                             0.6.1      
> mistune                            0.8.4      
> mkl-fft                            1.0.12     
> mkl-random                         1.0.2      
> mkl-service                        2.0.2      
> mock                               3.0.5      
> more-itertools                     7.0.0      
> mpmath                             1.1.0      
> msgpack                            0.6.1      
> multipledispatch                   0.6.0      
> multiprocess                       0.70.9     
> navigator-updater                  0.2.1      
> nbconvert                          5.5.0      
> nbformat                           4.4.0      
> networkx                           2.3        
> nltk                               3.4.4      
> nose                               1.3.7      
> notebook                           6.0.0      
> numba                              0.44.1     
> numexpr                            2.6.9      
> numpy                              1.16.4     
> numpydoc                           0.9.1      
> olefile                            0.46       
> openpyxl                           2.6.2      
> osqp                               0.6.1      
> packaging                          19.0       
> pandas                             0.24.2     
> pandas-datareader                  0.8.1      
> pandocfilters                      1.4.2      
> parso                              0.5.0      
> partd                              1.0.0      
> path.py                            12.0.1     
> pathlib2                           2.3.4      
> patsy                              0.5.1      
> pep8                               1.7.1      
> pexpect                            4.7.0      
> pickleshare                        0.7.5      
> Pillow                             6.1.0      
> pip                                19.1.1     
> pkginfo                            1.5.0.1    
> pluggy                             0.12.0     
> ply                                3.11       
> prometheus-client                  0.7.1      
> prompt-toolkit                     2.0.9      
> psutil                             5.6.3      
> ptyprocess                         0.6.0      
> py                                 1.8.0      
> pycodestyle                        2.5.0      
> pycosat                            0.6.3      
> pycparser                          2.19       
> pycrypto                           2.6.1      
> pycurl                             7.43.0.3   
> pyflakes                           2.1.1      
> Pygments                           2.4.2      
> pylint                             2.3.1      
> pyodbc                             4.0.26     
> pyOpenSSL                          19.0.0     
> pyparsing                          2.4.0      
> pyrsistent                         0.14.11    
> PySocks                            1.7.0      
> pytest                             5.0.1      
> pytest-arraydiff                   0.3        
> pytest-astropy                     0.5.0      
> pytest-doctestplus                 0.3.0      
> pytest-openfiles                   0.3.2      
> pytest-remotedata                  0.3.1      
> python-dateutil                    2.8.0      
> pytz                               2019.1     
> PyWavelets                         1.0.3      
> PyYAML                             5.1.1      
> pyzmq                              18.0.0     
> QtAwesome                          0.5.7      
> qtconsole                          4.5.1      
> QtPy                               1.8.0      
> Quandl                             3.5.0      
> requests                           2.22.0     
> rope                               0.14.0     
> ruamel-yaml                        0.15.46    
> scikit-image                       0.15.0     
> scikit-learn                       0.21.2     
> scipy                              1.4.1      
> scs                                2.1.1.post2
> seaborn                            0.9.0      
> SecretStorage                      3.1.1      
> Send2Trash                         1.5.0      
> setuptools                         45.2.0     
> simplegeneric                      0.8.1      
> singledispatch                     3.4.0.3    
> six                                1.12.0     
> snowballstemmer                    1.9.0      
> sortedcollections                  1.1.2      
> sortedcontainers                   2.1.0      
> soupsieve                          1.8        
> Sphinx                             2.1.2      
> sphinxcontrib-applehelp            1.0.1      
> sphinxcontrib-devhelp              1.0.1      
> sphinxcontrib-htmlhelp             1.0.2      
> sphinxcontrib-jsmath               1.0.1      
> sphinxcontrib-qthelp               1.0.2      
> sphinxcontrib-serializinghtml      1.1.3      
> sphinxcontrib-websupport           1.1.2      
> spyder                             3.3.6      
> spyder-kernels                     0.5.1      
> SQLAlchemy                         1.3.5      
> statsmodels                        0.10.0     
> sympy                              1.4        
> tables                             3.5.2      
> tblib                              1.4.0      
> terminado                          0.8.2      
> testpath                           0.4.2      
> toolz                              0.10.0     
> tornado                            6.0.3      
> tqdm                               4.32.1     
> traitlets                          4.3.2      
> unicodecsv                         0.14.1     
> urllib3                            1.24.2     
> wcwidth                            0.1.7      
> webencodings                       0.5.1      
> Werkzeug                           0.15.4     
> wheel                              0.34.2     
> widgetsnbextension                 3.5.0      
> wrapt                              1.11.2     
> wurlitzer                          1.0.2      
> xlrd                               1.2.0      
> XlsxWriter                         1.1.8      
> xlwt                               1.3.0      
> zict                               1.0.0      
> zipp                               0.5.1

**Comment by enzobusseti** [comment]
Hi! Thanks for trying `cvxportfolio`. Unfortunately the examples are currently broken, for a variety of reasons (not least, the data provider we chose has stopped serving data). If you install an early version of `cvxportfolio`, *e.g.*, 0.0.5, the code in the examples should work, minus some troubles with `pandas` and `cvxpy`, which also had non-backward-compatible changes. Otherwise, just wait, I'm in the midst of rewriting some core parts and will provide examples once I'm done.

**Comment by gobbedy** [comment]
Hi @enzobusseti, Do you need any help with rewriting core parts? It would be an opportunity for me to get familiar with the code. I would like to use in a personal project and if I could get my hands dirty with some fixes I'd be glad to make that contribution. I'm also planning to add cVaR as a risk measuring, which you may or may not be interested in as a contribution.

In the meantime I do have HelloWorld and another example working locally with a hackish fix to the latest (github) version of cvxportofolio and reverting to some older versions of packages of pandas and cvxpy. 

Also, may I suggest in the future modifying setup.py to get a coherent set up of packages? Currently, the relevant part of your setup.py reads
```
    install_requires=["pandas",
                      "numpy",
                      "matplotlib",
                      "cvxpy>=1.0.6"],
```
Whenever you get the examples back up and running, may I suggest setting the above packages to specific versions that are known to work, with an "install different packages at your own risk" notice in the readme.

I'd be happy to do that for you if you like.

This would allow future proofing of the installation, and newcomers would no longer bother you with problems coming in as newer packages break compatibility.

**Comment by zevnicsca** [comment]
@gobbedy can you please post what versions you ended up settling on? I have been trying to sort this out as well but with no luck. Thanks!

**Comment by gobbedy** [comment]
@zevnicsca I had to make manual fixes to the code, but they are ad-hoc for my particular needs and probably introduce other bugs since I was not concerned about other users. As far as I know, all versions are broken, and support does not seem to be forthcoming.
