### ISSUE TITLE
Risk model for MPO

### ISSUE THREAD

**Issue by avocadotruck94** [cvxgrp/cvxportfolio#48]
Hi, 

I am trying to run an mpo example and would like to use the FullSigma risk model. I am passing a prediction vector for each period created like all_return_estimates in the MultiPeriodOptimization example. I would like to pass an associated full sigma for each period. I am currently doing this using the same dictionary format as the return estimates. This does not seem to work. Is it possible to pass multiple sigmas, one for each period? If so, what format should be used? (In the code comments, there seems to be a reference to the obsolete pd.Panel format) 

Thanks.

**Comment by enzobusseti** [comment]
Hi! I'm currently fixing MPO, which relied on Pandas panels originally. It will accept data in the form of callable objects with two arguments: the time `t` of trading, and the step ahead of MPO. It will be clearer once I have some time to write it down.
