### ISSUE TITLE
fix some minor bugs in source code/examples/tests

### ISSUE THREAD

**Issue by walkacross** [cvxgrp/cvxportfolio#5]
hello @enzobusseti @SteveDiamond @jonathanng 

thank you for providing this great framework for portfolio optimization. I am wondering would you mind spent a little time fixing some minor bugs in source code and in examples/tests.

Some bugs likes:
(1) Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr.

(2) ValueError: Incompatible dimensions (430, 1) (431, 1)

(3) parameter name mistake, like returns_forecast and alpha_model.

(4) the first argument of SPO policy in SPO examples.

thanks for your time and have a good day.

**Comment by jonathanng** [comment]
Try the examples in my branch. Those should work.

**Comment by sunilshah** [comment]
Hi @jonathanng,

Thanks for getting back. 

I tried your master branch (https://github.com/jonathanng/cvxportfolio, latest commit).  My earlier comments are about the examples and the code in that branch (using the latest available versions of python 3.6 and notebook on Homebrew).  

HelloWorld errors out in call to MarketSimulator: 

 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-dfcfb978dfbb> in <module>()
      2     market_returns = returns,
      3     costs          = [tcost_model, hcost_model],
----> 4     cash_key       = 'USDOLLAR'
      5 ) 
      6 

TypeError: __init__() got an unexpected keyword argument 'market_returns'

Upon correcting the keyword to your March 2 commit, the notebook runs and gives reasonable results.

PortfolioSimulation.ipynb also needs the same correction. However, it generates results that are very different ( Active Risk at 19.3%) from those in the notebook on github. 

SinglePeriodOptimization also generates very different results after the keyword correction.  Most of the results of coarse search have very large negative excess returns.    

Please re-run the examples.  If you post the corrections in your branch I will be happy to test them out.

**Comment by enzobusseti** [comment]
I did a bug-fixing pass, I believe everything in the examples works right now.

**Comment by jpiter** [comment]
Can you please let me know where I can find fixed examples. It's been a year, so I assume the master branch must have been updated, but I still see the same error  on  MPOReturnsForecast with abstract methods weight_expr. TIA.

**Comment by esvhd** [comment]
> I did a bug-fixing pass, I believe everything in the examples works right now.

Hi @enzobusseti, 

I'm still running into problems trying to instiantiate `MPOReturnsForecast` class as well after cloning and installing the latest `master` branch here. Is the fix here simply to create a dummy `weight_expr()` method for the class since it's not being used?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-d1b92aa49092> in <module>
----> 1 returns_forecast = cp.MPOReturnsForecast(all_return_estimates)
      2 results_MPO={}

TypeError: Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr
```
