### ISSUE TITLE
share calculation in RealTimeOptimization

### ISSUE THREAD

**Issue by yz77** [cvxgrp/cvxportfolio#55]
Correct me if I am wrong - but I felt there is a bug in the share calculation in this example. It makes more sense to use t-1 close price to calculate the shares instead of t (as shown in the example), in other words - prices.shift(1). Since your decision price is last close - and in the propagation the assumption is filled at previous close and propagated by close to close return.

**Comment by joseortiz3** [comment]
You're going to need to provide some more detail for useful feedback.
