### ISSUE TITLE
MPO example is introducing future data

### ISSUE THREAD

**Issue by chloe-wang** [cvxgrp/cvxportfolio#56]
it looks like the MPO example is using the future return data, since it's impossible to know the exact return estimate for time t+1 at time t. This may make the comparison between SPO and MPO unfair.

![image](https://user-images.githubusercontent.com/22490931/83962287-d7794600-a8ce-11ea-9f06-99ed1d19b433.png)

![image](https://user-images.githubusercontent.com/22490931/83962480-5fac1b00-a8d0-11ea-8969-c2226ad87614.png)

**Comment by kch382001** [comment]
It is the return forecast of time t+1  while you are at time t.  It is a MPO, so you have return forecast for each forward period.  In comparison, SPO is single period therefore it has a single period return forecast.

**Comment by chloe-wang** [comment]
> It is the return forecast of time t+1 while you are at time t. It is a MPO, so you have return forecast for each forward period. In comparison, SPO is single period therefore it has a single period return forecast.
> […](#)
> Sent from my iPhone
> On Jun 7, 2020, at 3:09 AM, chloe-wang ***@***.***> wrote: it looks like the MPO example is using the future return data, since it's impossible to know the exact return estimate for time t+1 at time t. This may make the comparison between SPO and MPO unfair. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi thanks. I understand we have the the forecast for each forward period. but in the MPO example, it looks like we are using the forecast from SPO at time t+1, which is not available at time t actually in practical world.  I understand it's  for demonstration only, but it may make the conclusion that MPO is better than SPO unconvincing.
