### ISSUE TITLE
Should I assume this project is dead?

### ISSUE THREAD

**Issue by thayes75** [cvxgrp/cvxportfolio#60]
Hi all,

While it seems there was a small push about a year ago to update the project, there are far too many broken issues (benchmarks don't work, for example). Should I assume this project is dead/abandoned?

Cheers

**Comment by avocadotruck94** [comment]
Judging from the response so far probably yes. I'm still using this but constantly having to fix/workaround some issues. Will try making a pull request if I manage to write a good fix for something but no promises.

**Comment by roprisor** [comment]
Actually, I have a version that works with most of the latest packages (as of Nov/Dec 2020 at least), I'll look to share it by the end of the week.
I also created this helper lib that outputs directly what cvxportfolio needs to run optimizations: https://github.com/roprisor/alphamodel. There are a few example notebooks so it should be straightforward to use.

**Comment by thayes75** [comment]
I would definitely be interested. I have some kludges I was working on for the factorized risk model, but the two things I could not figure out was:

- The DollarNeutral constraint never seemed to work
- Passing a benchmark as a dataframe (i.e. weights for each dates/IDs)

**Comment by avocadotruck94** [comment]
Would also be interested, currently struggling with below error on all of my machines (except one)

```
Traceback (most recent call last):
  File "/home/bob/jalouse/main.py", line 171, in <module>
    run(3)
  File "/home/bob/jalouse/main.py", line 167, in run
    return func()
  File "/home/bob/jalouse/main.py", line 150, in sim
    sim_function(info)
  File "/home/bob/jalouse/sim.py", line 1109, in sim_function
    port_results = mpo_market_sim(Date, returns, all_return_estimates, sigmas_hat_residuals, all_sigmas_estimates,
  File "/home/bob/jalouse/portfolio_opt.py", line 911, in mpo_market_sim
    returns_forecast = cp.MPOReturnsForecast(all_return_estimates)
TypeError: Can't instantiate abstract class MPOReturnsForecast with abstract methods weight_expr
```

Reviewed similar issues in
https://github.com/cvxgrp/cvxportfolio/issues/34
https://github.com/cvxgrp/cvxportfolio/issues/22

but no luck

**Comment by enzbus** [comment]
Hello, the project is being restored now. Basic testing passes and two example notebooks (see https://cvxportfolio.readthedocs.io/en/latest/examples/index.html) run. Please be patient as we fix the rest.
