### ISSUE TITLE
Issue while reading the risk_model.h5

### ISSUE THREAD

**Issue by pawansnegi** [cvxgrp/cvxportfolio#64]
I am getting this error 

    TypeError: cannot properly create the storer for: [_STORER_MAP] [group->/exposures (Group) '',value-><class 
    'NoneType'>,format->None

while reading the file `risk_model.py`.

Is it a known problem?

**Comment by JXY-hub** [comment]
Hello, I also encountered this problem,Have you solved this problem？

**Comment by SteveDiamond** [comment]
This package is basically deprecated. Take a look at "pyportfolioopt".

**Comment by JXY-hub** [comment]
ok, thank you very much！
