### ISSUE TITLE
Publish sdist or tag releases on GitHub for conda forge

### ISSUE THREAD

**Issue by timkpaine** [cvxgrp/cvxportfolio#67]
Conda forge prefers source distributions rather than wheels. Either an sdist on pypi or a git tag on GitHub.

**Comment by enzbus** [comment]
Hello, yes, we dropped conda support and are only doing PyPI now. Thanks!

**Comment by enzbus** [comment]
I think your recipe needs updating, let me send you a PR. (Sdists instead of wheels and slightly changed requirements.)
