### ISSUE TITLE
Single Period Optimization example code doesn't run

### ISSUE THREAD

**Issue by arman-zhumakhan** [cvxgrp/cvxportfolio#72]
When I tried to run SinglePeriodOptimization.ipynb, it didn't work.

I got this error
```
ValueError: Cannot broadcast dimensions  (60, 432) (432,)
```

**Comment by enzbus** [comment]
Hello, the SPO notebook is currently broken but we're working on fixing it. To see working examples look at
https://github.com/cvxgrp/cvxportfolio/blob/master/examples/HelloWorld.ipynb
and
https://github.com/cvxgrp/cvxportfolio/blob/master/examples/MultiPeriodTCostOptimization.ipynb
keep in mind that the user interface is still subject to change.
