### ISSUE TITLE
run isort

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxportfolio#77]
in general read up pre-commit (black should not be dev dependency). Isort and black should be executed on the fly when committing code.

**Comment by tschm** [comment]
easy way would be to integrate with deepsource. see tschm/antarctic or tschm/tinycta

**Comment by enzbus** [comment]
Using autopep8 for PEP8 compliance, not enforcing any particular code style. If people write MR pytest passing is only enforced condition.
