### ISSUE TITLE
yfinance and pandas-datareader

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxportfolio#78]
I don't think they should be dependencies. Supporting yahoo etc. is something the packages doesn't need to do. Could be an example in a notebook demonstrating how to overload the base class but the package should stop at the baseclass.

**Comment by enzbus** [comment]
These are used by the new simulator logic to download automatically (and store locally) assets' returns and volumes and cash return, which then populate estimates (for example for tcost parameters). The code is already written in `cvxportfolio.data` and hasn't been integrated in the simulator yet.
