### ISSUE TITLE
Feature: volume-based commission option

### ISSUE THREAD

**Issue by quant9** [cvxgrp/cvxportfolio#80]
`per_share_fixed_cost` is not applicable to some markets, which charge commissions by dollar volume transacted instead of shares.

Suggest an option to have trading costs as a % of volume.

Thanks for revitalizing this project!

**Comment by enzbus** [comment]
Hello and thanks! If I understand your question correctly you can model any cost linear in the size of the trades with the `spreads` (float, Series, or DataFrame) argument to both MarketSimulator and Single/MultiPeriodOptimization. It may make sense to rename it from spreads to linear_cost or something like that.

**Comment by quant9** [comment]
I see - that makes sense as the spread can be thought of as a linear cost. I will leave it to you to decide on naming. thanks.

**Comment by enzbus** [comment]
TODO: rename spreads in TransactionCost and simulator's transaction cost to (probably) `linear_cost`
