### ISSUE TITLE
universe (and r_hat) requires cash column

### ISSUE THREAD

**Issue by quant9** [cvxgrp/cvxportfolio#81]
This is more to deepen my understanding rather than to raise an issue.

I noticed that the `universe` parameter includes cash - e.g., USDOLLAR - which means that `r_hat_parameter` is of size n+1. This means that the return estimates passed to `r_hat` must include an estimate of cash returns (see line below):

https://github.com/cvxgrp/cvxportfolio/blob/master/cvxportfolio/returns.py#L177

Would it be appropriate just to populate a USDOLLAR column of zeros in and pass it into `r_hat`? Would there be any undesired / unintended impact of this, e.g., in periods where return estimates for the other (actual) assets are skewed far away from zero?

Thanks!

**Comment by quant9** [comment]
Yeah, wouldn't bother if it's a problem that doesn't need solving (e.g., 99% of users expect to use yfinance anyways). Initial thought of downloading from FRED makes sense.

btw, I'm happy to contribute to the repo in near future (in addition to just raising issues) once I get comfortable with the intricacies.

**Comment by enzbus** [comment]
Thanks @quant9 ! 

Spotting issues and incongruences is a great contribution, and if you have time to read the code that's great as well! I should add a development section to the readme (will do it now). Major things I'm working on now are refactoring the simulator module (it is too big and needs to be broken down into pieces); the data module is mostly unused (I thought of including database support but it's too tricky, pickle is better and faster for on-disk caching), the estimator logic (recursive tree for compilation and parameter update) is in fact a bit intricate but I don't think it's too bad (and I just found out I can set numpy arrays to read only so it's going to become also quite safe). 

In general the goals are: (1) small codebase (2) readability and auditability (3) ease of subclassing for custom usecases.
