### ISSUE TITLE
Best practices for dealing with nan assets (e.g., IPOs)

### ISSUE THREAD

**Issue by quant9** [cvxgrp/cvxportfolio#85]
I have noticed that having assets containing leading NaNs in a portfolio causes the simulator to fail.

This poses challenges for the common use case of backtesting on universes containing NaNs, especially leading NaNs (for instance, IPOs).

Curious on what the best practices for handling this are? Thanks

**Comment by quant9** [comment]
Follow-on comment:
The simulator doesn't fail if only internal pricing is used, but the new assets are not represented in the ptf at all.

Code snippet (using the sample code in readme):
```
simulator = cp.MarketSimulator(['AAPL', 'AMZN', 'TSLA', 'GM', 'CVX', 'UBER'])
backtest = simulator.backtest(policy, start_time='2019-01-01', end_time='2021-04-01')  # UBER went public in mid-2019
```

Results:
<img width="421" alt="image" src="https://github.com/cvxgrp/cvxportfolio/assets/4811862/df90fedc-cc0f-46fd-9623-196475670048">

**Comment by enzbus** [comment]
This should work now, you can test with the ``hello_world.py`` in the repo (I added $UBER as you suggested). It's quite difficult to do in fact, but at least for IPOs it should already be correct.
