### ISSUE TITLE
Memory Error When use more than two policiy

### ISSUE THREAD

**Issue by Zhangwuhao** [cvxgrp/cvxportfolio#98]
I use pycharm to test pyscript. 

As documents say, it will be a multiprocess when pass policy list. <br>
When I pass it, the program is all right when I test it with scientific model in pycharm. <br>
But it crash when I test it with terminal or console, and the error information is Memory Error. 

But if it can work in scientific mode, there should not be problem with RAM. Do you know why this happen? Thank you vey much.

**Comment by enzbus** [comment]
Can you post a script that shows the error? And which version are you using? You can also try with the ``parallel=False`` option to the backtest method.
