### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by enzbus** [cvxgrp/cvxportfolio#99]
https://peps.python.org/pep-0008

# Before EOM user interface freeze
- massive rename of private attributes with leading underscore
- user-facing names should reflect usage not implementation
- double-check all names against rules

# Other
- add `flake8` to test pipeline

**Comment by quant9** [comment]
In addition to PEP8, I am a huge fan of Black (https://black.readthedocs.io/en/stable/). It is PEP8 compliant.
Should we enforce it as well?

**Comment by enzbus** [comment]
Tried it, no thanks; It's unpythonic. I get that Python is acquiring many coders from other languages (with a different mindset about what code is I guess) but it's very bad to restrict the language for something as stupid as how it looks like. Readability is mostly about good naming choices and well-factored code (short methods, ...), not single vs. double quotes 😂
